# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3010582697242df1827ffad85757c26a3c0b9c33e9a0b1d96dfabab9afcefcce9c6d9ace3d7952eac303628ebbae1a3fe98be53b1a96117cdf33a5fc195f73be

test:
  secret_key_base: fa808251e5f2bf1377bd5430fae28a562ac0c7bfe712d895e909d559e1d84833a5d1d92c78dfc22b30eb0ae6a86f26fc622873590f1c0e051675b36e2d895568

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
